### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by avindra** [davidyaha/ecmascript-optionals-proposal#1]
Thanks for putting this together!

Do you know what's the status of making this an official tc39 proposal? Is there anything we can help out with?

**Comment by davidyaha** [comment]
Hey @avindra,
Thanks for the support.
[The official suggestion](https://github.com/claudepache/es-optional-chaining) by @claudepache was recently got to stage-1 a couple of weeks ago
@gisenberg is the champion leading this proposal and you can see on [issue 328 of babylon](https://github.com/babel/babylon/issues/328) that he is working on a babel plugin as well.
Just now I've sent him a message on babeljs slack in order to help out.

Once babylon will merge the syntax addition I would be able to change this plugin to support it or rather scrap this and use the work done by @gisenberg. 
This other suggestion has a bit different syntax for function calls and dynamic member expressions (obj['field']) but the idea is the same, so you will be able to start using that.

Hope this helps to get where this stands and LMK if you have more questions.

**Comment by kristofdegrave** [comment]
@davidyaha I'm working on a PR for babylon, but I was wondering how you want it to look like?
I have 2 options for passing if it is optional. I can put it on the MemberExpression or I can put it on the object property of the Member expression. This since the optional is talking about the object...

Second thing I would like to know is how the proposal will evolve. I see in some cases they are talking about using `?.` for everything `x?.y` `x?.["a"]` `func?.()`. Or as you propose use `x?["a"]` `func?()` which I personally prefer more :).

**Comment by davidyaha** [comment]
I also prefer the later syntax but browsers might have a hard time implementing it.
I've contacted @gisenberg (the tc39 champion of the null propagation operator proposal) in order to coordinate work.
I suggest you to do the same. He is available on the babeljs slack.
From what I gathered, the official stage-1 spec text is underway but it is neither this repo, nor Claude's.
Please help us move this proposal forward by chiming in and talk with the champion, so that he could do what he was assigned with.

Thanks for your work thus far!

**Comment by avindra** [comment]
#proposal-opt-chaining on the babeljs slack was created 3 days ago to discuss this topic ❤️

**Comment by davidyaha** [comment]
https://github.com/tc39/proposal-optional-chaining

**Comment by Fire-Dragon-DoL** [comment]
I can't describe how easier this would make to migrate all old coffeescript codebases to proper ecmascript I really hope it gets through
